### ISSUE TITLE
IPCP Pro XI Series

### ISSUE THREAD

**Issue by av-guy** [GrantGMiller/gs_http_server#1]
Hi Grant,

This is not really an issue as much as it is a question. I noticed that the newer XI model processors have much fewer disallowed non-built ins and built-ins. Would it be possible to use the built-in http module to create an HTTP server inside of the XI processor?

Thanks for any info you can provide.

**Comment by GrantGMiller** [comment]
@av-guy 
I finally got my hands on a QXI processor to play around with.
There are definitely some libraries that have been unlocked in the XI FW that are helpful. 
For example the `http.server.BaseHTTPRequestHandler` could replace my manual HTTP Request parsing.
Combining with `socketserver.TCPServer` could most likely improve performance.

You are still blocked from `pip install xxxx` which means you cannot simply something like `flask` or `django` .

I definitely recommend anyone with a QXI processor to setup the basic HTTP example from python.org and poke around.
```
import http.server
import socketserver

PORT = 8000

Handler = http.server.SimpleHTTPRequestHandler

with socketserver.TCPServer(("", PORT), Handler) as httpd:
    print("serving at port", PORT)
    httpd.serve_forever()
```

Thanks for your feedback. Please keep in touch.

**Comment by av-guy** [comment]
Thank you for taking the time out of your day to answer my question. It is appreciated.
