### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by av-guy** [GrantGMiller/gs_http_server#2]
Hey Grant,

Am I able to use this project in production? I have a project that needs a web server, and I feel like this would be perfect.

**Comment by GrantGMiller** [comment]
Short answer: yes, feel free to use it in production.
I have added a MIT License to this project to make it more explicit that I welcome its use by anyone who wants to.
If you have any questions about your specific use-case, let me know.

**Comment by av-guy** [comment]
Thanks Grant. I'll close out this issue.
